In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

In [2]:
students = pd.read_csv("D:\c drive 16.07.26\Desktop\Power bi\Indian_Student_AI_Dataset.csv")
print(students)

     student_id  age  gender       city      branch  year_of_study  cgpa  \
0      STU00001   17  Female     Mumbai        ENTC              3  8.56
1      STU00002   19  Female     Nagpur       Civil              2  8.51
2      STU00003   28  Female     Mumbai         CSE              2  7.25
3      STU00004   21  Female     Nagpur        ENTC              2  9.24
4      STU00005   27  Female     Nagpur        ENTC              3  6.79
...         ...  ...     ...        ...         ...            ...   ...
2995   STU02996   20    Male    Kolkata        ENTC              3  8.28
2996   STU02997   25    Male  Hyderabad       AI/ML              3  6.21
2997   STU02998   23    Male    Chennai  Electrical              4  6.50
2998   STU02999   18  Female  Bangalore       AI/ML              1  9.32
2999   STU03000   19  Female  Hyderabad       Civil              3  9.63

      daily_study_hours  daily_chatgpt_usage_hours  daily_coding_hours  \
0                   3.6                        4.4                 6.5
1                   5.3                        2.7                 6.6
2                   7.6                        1.4                 4.8
3                   7.5                        5.8                 2.9
4                   6.7                        3.5                 3.9
...                 ...                        ...                 ...
2995                7.4                        2.3                 2.1
2996                3.8                        7.7                 4.9
2997                9.4                        7.0                 7.9
2998                8.8                        7.3                 0.4
2999                7.7                        4.4                 0.7

     favorite_ai_tool ai_dependency_level  productivity_score  stress_level  \
0             ChatGPT                 Low                  64             9
1              Gemini                 Low                  97             7
2              Gemini                 Low                  58             7
3          Perplexity                High                  73            10
4          Perplexity                 Low                  94             3
...               ...                 ...                 ...           ...
2995          ChatGPT                 Low                  78             8
2996          ChatGPT                 Low                  65             8
2997   GitHub Copilot                 Low                  52             6
2998          ChatGPT                 Low                  95             8
2999          ChatGPT                 Low                  98             6

      sleep_hours placement_status  expected_salary_lpa  \
0             6.1       Internship                34.38
1             6.2           Placed                 4.91
2             6.7       Internship                23.30
3             5.8       Not Placed                10.30
4             6.5       Internship                16.63
...           ...              ...                  ...
2995          8.6           Placed                26.09
2996          7.1           Placed                23.23
2997          5.1           Placed                25.05
2998          8.2       Internship                22.46
2999          8.0           Placed                21.27

     preferred_programming_language  mental_wellbeing_score  \
0                               C++                      36
1                              Java                      30
2                               C++                      90
3                        JavaScript                      95
4                        JavaScript                      63
...                             ...                     ...
2995                         Python                      75
2996                     JavaScript                      34
2997                     JavaScript                      66
2998                           Java                      76
2999                           Java                      40

      ai_replaceability_fear
0                          3
1                          6
2                          1
3                          7
4                          3
...                      ...
2995                       6
2996                      10
2997                       2
2998                       8
2999                       1

[3000 rows x 20 columns]

In [3]:
# To see the first 10 rows
students.head(10)

,student_id,age,gender,city,branch,year_of_study,cgpa,daily_study_hours,daily_chatgpt_usage_hours,daily_coding_hours,favorite_ai_tool,ai_dependency_level,productivity_score,stress_level,sleep_hours,placement_status,expected_salary_lpa,preferred_programming_language,mental_wellbeing_score,ai_replaceability_fear
0,STU00001,17,Female,Mumbai,ENTC,3,8.56,3.6,4.4,6.5,ChatGPT,Low,64,9,6.1,Internship,34.38,C++,36,3
1,STU00002,19,Female,Nagpur,Civil,2,8.51,5.3,2.7,6.6,Gemini,Low,97,7,6.2,Placed,4.91,Java,30,6
2,STU00003,28,Female,Mumbai,CSE,2,7.25,7.6,1.4,4.8,Gemini,Low,58,7,6.7,Internship,23.30,C++,90,1
3,STU00004,21,Female,Nagpur,ENTC,2,9.24,7.5,5.8,2.9,Perplexity,High,73,10,5.8,Not Placed,10.30,JavaScript,95,7
4,STU00005,27,Female,Nagpur,ENTC,3,6.79,6.7,3.5,3.9,Perplexity,Low,94,3,6.5,Internship,16.63,JavaScript,63,3
5,STU00006,22,Female,Nagpur,CSE,4,6.87,4.8,7.6,4.5,GitHub Copilot,High,89,6,7.1,Placed,6.70,Java,76,1
6,STU00007,22,Male,Kolkata,Mechanical,1,6.90,4.7,2.0,4.3,Claude,Medium,88,4,8.9,Internship,19.62,Python,49,9
7,STU00008,24,Female,Ahmedabad,CSE,2,8.20,2.1,4.8,4.9,GitHub Copilot,Low,41,5,5.7,Not Placed,12.73,JavaScript,83,1
8,STU00009,18,Male,Nagpur,Civil,1,7.33,7.1,4.1,6.0,ChatGPT,Medium,97,1,6.9,Internship,23.00,Java,99,7
9,STU00010,17,Female,Hyderabad,CSE,3,8.47,8.6,6.1,2.2,GitHub Copilot,Medium,41,3,5.0,Not Placed,21.32,Python,77,4

In [4]:
# To see the last 5 rows
students.tail(5)

,student_id,age,gender,city,branch,year_of_study,cgpa,daily_study_hours,daily_chatgpt_usage_hours,daily_coding_hours,favorite_ai_tool,ai_dependency_level,productivity_score,stress_level,sleep_hours,placement_status,expected_salary_lpa,preferred_programming_language,mental_wellbeing_score,ai_replaceability_fear
2995,STU02996,20,Male,Kolkata,ENTC,3,8.28,7.4,2.3,2.1,ChatGPT,Low,78,8,8.6,Placed,26.09,Python,75,6
2996,STU02997,25,Male,Hyderabad,AI/ML,3,6.21,3.8,7.7,4.9,ChatGPT,Low,65,8,7.1,Placed,23.23,JavaScript,34,10
2997,STU02998,23,Male,Chennai,Electrical,4,6.50,9.4,7.0,7.9,GitHub Copilot,Low,52,6,5.1,Placed,25.05,JavaScript,66,2
2998,STU02999,18,Female,Bangalore,AI/ML,1,9.32,8.8,7.3,0.4,ChatGPT,Low,95,8,8.2,Internship,22.46,Java,76,8
2999,STU03000,19,Female,Hyderabad,Civil,3,9.63,7.7,4.4,0.7,ChatGPT,Low,98,6,8.0,Placed,21.27,Java,40,1

In [5]:
# To see all the column names
students.columns

Index(['student_id', 'age', 'gender', 'city', 'branch', 'year_of_study',
       'cgpa', 'daily_study_hours', 'daily_chatgpt_usage_hours',
       'daily_coding_hours', 'favorite_ai_tool', 'ai_dependency_level',
       'productivity_score', 'stress_level', 'sleep_hours', 'placement_status',
       'expected_salary_lpa', 'preferred_programming_language',
       'mental_wellbeing_score', 'ai_replaceability_fear'],
      dtype='object')

In [6]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 20 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   student_id                      3000 non-null   object
 1   age                             3000 non-null   int64
 2   gender                          3000 non-null   object
 3   city                            3000 non-null   object
 4   branch                          3000 non-null   object
 5   year_of_study                   3000 non-null   int64
 6   cgpa                            3000 non-null   float64
 7   daily_study_hours               3000 non-null   float64
 8   daily_chatgpt_usage_hours       3000 non-null   float64
 9   daily_coding_hours              3000 non-null   float64
 10  favorite_ai_tool                3000 non-null   object
 11  ai_dependency_level             3000 non-null   object
 12  productivity_score              3000 non-null   int64
 13  stress_level                    3000 non-null   int64
 14  sleep_hours                     3000 non-null   float64
 15  placement_status                3000 non-null   object
 16  expected_salary_lpa             3000 non-null   float64
 17  preferred_programming_language  3000 non-null   object
 18  mental_wellbeing_score          3000 non-null   int64
 19  ai_replaceability_fear          3000 non-null   int64
dtypes: float64(6), int64(6), object(8)
memory usage: 468.9+ KB

In [7]:
students.describe()

,age,year_of_study,cgpa,daily_study_hours,daily_chatgpt_usage_hours,daily_coding_hours,productivity_score,stress_level,sleep_hours,expected_salary_lpa,mental_wellbeing_score,ai_replaceability_fear
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,22.545333,2.484333,7.712243,5.511400,4.058467,4.443433,70.198667,5.429333,6.488200,18.720813,65.080000,5.514333
std,3.480323,1.120196,1.278730,2.602927,2.295444,2.592881,17.714527,2.850330,1.439849,9.146084,20.392406,2.894464
min,17.000000,1.000000,5.500000,1.000000,0.000000,0.000000,40.000000,1.000000,4.000000,3.000000,30.000000,1.000000
25%,20.000000,1.000000,6.580000,3.200000,2.100000,2.200000,55.000000,3.000000,5.200000,10.870000,48.000000,3.000000
50%,23.000000,2.000000,7.730000,5.500000,4.200000,4.500000,70.000000,5.000000,6.500000,18.780000,65.000000,6.000000
75%,26.000000,3.000000,8.812500,7.800000,6.000000,6.700000,85.000000,8.000000,7.700000,26.472500,83.000000,8.000000
max,28.000000,4.000000,9.900000,10.000000,8.000000,9.000000,100.000000,10.000000,9.000000,34.970000,100.000000,10.000000

In [8]:
# To see the number of rows in the table
len(students)

3000

In [9]:
students.shape

(3000, 20)

In [10]:
# To see particular rows
students.iloc[0]

student_id                          STU00001
age                                       17
gender                                Female
city                                  Mumbai
branch                                  ENTC
year_of_study                              3
cgpa                                    8.56
daily_study_hours                        3.6
daily_chatgpt_usage_hours                4.4
daily_coding_hours                       6.5
favorite_ai_tool                     ChatGPT
ai_dependency_level                      Low
productivity_score                        64
stress_level                               9
sleep_hours                              6.1
placement_status                  Internship
expected_salary_lpa                    34.38
preferred_programming_language           C++
mental_wellbeing_score                    36
ai_replaceability_fear                     3
Name: 0, dtype: object

In [11]:
# To check if there are any missing values in the table
students.isnull()

,student_id,age,gender,city,branch,year_of_study,cgpa,daily_study_hours,daily_chatgpt_usage_hours,daily_coding_hours,favorite_ai_tool,ai_dependency_level,productivity_score,stress_level,sleep_hours,placement_status,expected_salary_lpa,preferred_programming_language,mental_wellbeing_score,ai_replaceability_fear
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
students.isnull().sum()

student_id                        0
age                               0
gender                            0
city                              0
branch                            0
year_of_study                     0
cgpa                              0
daily_study_hours                 0
daily_chatgpt_usage_hours         0
daily_coding_hours                0
favorite_ai_tool                  0
ai_dependency_level               0
productivity_score                0
stress_level                      0
sleep_hours                       0
placement_status                  0
expected_salary_lpa               0
preferred_programming_language    0
mental_wellbeing_score            0
ai_replaceability_fear            0
dtype: int64

In [13]:
students.index

RangeIndex(start=0, stop=3000, step=1)

In [14]:
# To check if there are any students' records that are repeated
students.duplicated

<bound method DataFrame.duplicated of      student_id  age  gender       city      branch  year_of_study  cgpa  \
0      STU00001   17  Female     Mumbai        ENTC              3  8.56
1      STU00002   19  Female     Nagpur       Civil              2  8.51
2      STU00003   28  Female     Mumbai         CSE              2  7.25
3      STU00004   21  Female     Nagpur        ENTC              2  9.24
4      STU00005   27  Female     Nagpur        ENTC              3  6.79
...         ...  ...     ...        ...         ...            ...   ...
2995   STU02996   20    Male    Kolkata        ENTC              3  8.28
2996   STU02997   25    Male  Hyderabad       AI/ML              3  6.21
2997   STU02998   23    Male    Chennai  Electrical              4  6.50
2998   STU02999   18  Female  Bangalore       AI/ML              1  9.32
2999   STU03000   19  Female  Hyderabad       Civil              3  9.63

      daily_study_hours  daily_chatgpt_usage_hours  daily_coding_hours  \
0                   3.6                        4.4                 6.5
1                   5.3                        2.7                 6.6
2                   7.6                        1.4                 4.8
3                   7.5                        5.8                 2.9
4                   6.7                        3.5                 3.9
...                 ...                        ...                 ...
2995                7.4                        2.3                 2.1
2996                3.8                        7.7                 4.9
2997                9.4                        7.0                 7.9
2998                8.8                        7.3                 0.4
2999                7.7                        4.4                 0.7

     favorite_ai_tool ai_dependency_level  productivity_score  stress_level  \
0             ChatGPT                 Low                  64             9
1              Gemini                 Low                  97             7
2              Gemini                 Low                  58             7
3          Perplexity                High                  73            10
4          Perplexity                 Low                  94             3
...               ...                 ...                 ...           ...
2995          ChatGPT                 Low                  78             8
2996          ChatGPT                 Low                  65             8
2997   GitHub Copilot                 Low                  52             6
2998          ChatGPT                 Low                  95             8
2999          ChatGPT                 Low                  98             6

      sleep_hours placement_status  expected_salary_lpa  \
0             6.1       Internship                34.38
1             6.2           Placed                 4.91
2             6.7       Internship                23.30
3             5.8       Not Placed                10.30
4             6.5       Internship                16.63
...           ...              ...                  ...
2995          8.6           Placed                26.09
2996          7.1           Placed                23.23
2997          5.1           Placed                25.05
2998          8.2       Internship                22.46
2999          8.0           Placed                21.27

     preferred_programming_language  mental_wellbeing_score  \
0                               C++                      36
1                              Java                      30
2                               C++                      90
3                        JavaScript                      95
4                        JavaScript                      63
...                             ...                     ...
2995                         Python                      75
2996                     JavaScript                      34
2997                     JavaScript                      66
2998                           Java                      76
2999                           Java                      40

      ai_replaceability_fear
0                          3
1                          6
2                          1
3                          7
4                          3
...                      ...
2995                       6
2996                      10
2997                       2
2998                       8
2999                       1

[3000 rows x 20 columns]>

In [15]:
students.duplicated().sum()

np.int64(0)

In [16]:
import numpy as np

In [17]:
# To find and remove outliers
v = students.sort_values("age")

q1 = np.percentile(v['age'],25)
q2 = np.percentile(v['age'],50)
q3 = np.percentile(v['age'],75)
print(q1)
print(q2)
print(q3)

iqr = q3 - q1
print(iqr)

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr
print(lower)
print(upper)

outliers = students[(students['age'] < lower) | (students['age'] > upper)]
print(outliers)

20.0
23.0
26.0
6.0
11.0
35.0
Empty DataFrame
Columns: [student_id, age, gender, city, branch, year_of_study, cgpa, daily_study_hours, daily_chatgpt_usage_hours, daily_coding_hours, favorite_ai_tool, ai_dependency_level, productivity_score, stress_level, sleep_hours, placement_status, expected_salary_lpa, preferred_programming_language, mental_wellbeing_score, ai_replaceability_fear]
Index: []

In [18]:
# To add new columns
students['total_screen_time'] = (students['daily_coding_hours'] + students['daily_chatgpt_usage_hours']).round(2)

In [19]:
students.head(10)

,student_id,age,gender,city,branch,year_of_study,cgpa,daily_study_hours,daily_chatgpt_usage_hours,daily_coding_hours,...,ai_dependency_level,productivity_score,stress_level,sleep_hours,placement_status,expected_salary_lpa,preferred_programming_language,mental_wellbeing_score,ai_replaceability_fear,total_screen_time
0,STU00001,17,Female,Mumbai,ENTC,3,8.56,3.6,4.4,6.5,...,Low,64,9,6.1,Internship,34.38,C++,36,3,10.9
1,STU00002,19,Female,Nagpur,Civil,2,8.51,5.3,2.7,6.6,...,Low,97,7,6.2,Placed,4.91,Java,30,6,9.3
2,STU00003,28,Female,Mumbai,CSE,2,7.25,7.6,1.4,4.8,...,Low,58,7,6.7,Internship,23.30,C++,90,1,6.2
3,STU00004,21,Female,Nagpur,ENTC,2,9.24,7.5,5.8,2.9,...,High,73,10,5.8,Not Placed,10.30,JavaScript,95,7,8.7
4,STU00005,27,Female,Nagpur,ENTC,3,6.79,6.7,3.5,3.9,...,Low,94,3,6.5,Internship,16.63,JavaScript,63,3,7.4
5,STU00006,22,Female,Nagpur,CSE,4,6.87,4.8,7.6,4.5,...,High,89,6,7.1,Placed,6.70,Java,76,1,12.1
6,STU00007,22,Male,Kolkata,Mechanical,1,6.90,4.7,2.0,4.3,...,Medium,88,4,8.9,Internship,19.62,Python,49,9,6.3
7,STU00008,24,Female,Ahmedabad,CSE,2,8.20,2.1,4.8,4.9,...,Low,41,5,5.7,Not Placed,12.73,JavaScript,83,1,9.7
8,STU00009,18,Male,Nagpur,Civil,1,7.33,7.1,4.1,6.0,...,Medium,97,1,6.9,Internship,23.00,Java,99,7,10.1
9,STU00010,17,Female,Hyderabad,CSE,3,8.47,8.6,6.1,2.2,...,Medium,41,3,5.0,Not Placed,21.32,Python,77,4,8.3

In [20]:
students['productivity_per_screentime'] = (students['productivity_score'] / students['total_screen_time']).round(2)

In [21]:
students.head(5)

,student_id,age,gender,city,branch,year_of_study,cgpa,daily_study_hours,daily_chatgpt_usage_hours,daily_coding_hours,...,productivity_score,stress_level,sleep_hours,placement_status,expected_salary_lpa,preferred_programming_language,mental_wellbeing_score,ai_replaceability_fear,total_screen_time,productivity_per_screentime
0,STU00001,17,Female,Mumbai,ENTC,3,8.56,3.6,4.4,6.5,...,64,9,6.1,Internship,34.38,C++,36,3,10.9,5.87
1,STU00002,19,Female,Nagpur,Civil,2,8.51,5.3,2.7,6.6,...,97,7,6.2,Placed,4.91,Java,30,6,9.3,10.43
2,STU00003,28,Female,Mumbai,CSE,2,7.25,7.6,1.4,4.8,...,58,7,6.7,Internship,23.30,C++,90,1,6.2,9.35
3,STU00004,21,Female,Nagpur,ENTC,2,9.24,7.5,5.8,2.9,...,73,10,5.8,Not Placed,10.30,JavaScript,95,7,8.7,8.39
4,STU00005,27,Female,Nagpur,ENTC,3,6.79,6.7,3.5,3.9,...,94,3,6.5,Internship,16.63,JavaScript,63,3,7.4,12.70

In [22]:
# Trimming Extra Spaces
text_column = ["student_id","gender","city","branch","favorite_ai_tool",
               "ai_dependency_level","placement_status","preferred_programming_language"]

for c in text_column:
    students[c] = students[c].astype(str).str.strip()

In [23]:
students.columns = students.columns.str.strip().str.title()

In [24]:
students

,Student_Id,Age,Gender,City,Branch,Year_Of_Study,Cgpa,Daily_Study_Hours,Daily_Chatgpt_Usage_Hours,Daily_Coding_Hours,...,Productivity_Score,Stress_Level,Sleep_Hours,Placement_Status,Expected_Salary_Lpa,Preferred_Programming_Language,Mental_Wellbeing_Score,Ai_Replaceability_Fear,Total_Screen_Time,Productivity_Per_Screentime
0,STU00001,17,Female,Mumbai,ENTC,3,8.56,3.6,4.4,6.5,...,64,9,6.1,Internship,34.38,C++,36,3,10.9,5.87
1,STU00002,19,Female,Nagpur,Civil,2,8.51,5.3,2.7,6.6,...,97,7,6.2,Placed,4.91,Java,30,6,9.3,10.43
2,STU00003,28,Female,Mumbai,CSE,2,7.25,7.6,1.4,4.8,...,58,7,6.7,Internship,23.30,C++,90,1,6.2,9.35
3,STU00004,21,Female,Nagpur,ENTC,2,9.24,7.5,5.8,2.9,...,73,10,5.8,Not Placed,10.30,JavaScript,95,7,8.7,8.39
4,STU00005,27,Female,Nagpur,ENTC,3,6.79,6.7,3.5,3.9,...,94,3,6.5,Internship,16.63,JavaScript,63,3,7.4,12.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,STU02996,20,Male,Kolkata,ENTC,3,8.28,7.4,2.3,2.1,...,78,8,8.6,Placed,26.09,Python,75,6,4.4,17.73
2996,STU02997,25,Male,Hyderabad,AI/ML,3,6.21,3.8,7.7,4.9,...,65,8,7.1,Placed,23.23,JavaScript,34,10,12.6,5.16
2997,STU02998,23,Male,Chennai,Electrical,4,6.50,9.4,7.0,7.9,...,52,6,5.1,Placed,25.05,JavaScript,66,2,14.9,3.49
2998,STU02999,18,Female,Bangalore,AI/ML,1,9.32,8.8,7.3,0.4,...,95,8,8.2,Internship,22.46,Java,76,8,7.7,12.34
2999,STU03000,19,Female,Hyderabad,Civil,3,9.63,7.7,4.4,0.7,...,98,6,8.0,Placed,21.27,Java,40,1,5.1,19.22

In [25]:
# Renaming the column name
students = students.rename(columns = {"Cgpa" : "CGPA"})

In [26]:
students

,Student_Id,Age,Gender,City,Branch,Year_Of_Study,CGPA,Daily_Study_Hours,Daily_Chatgpt_Usage_Hours,Daily_Coding_Hours,...,Productivity_Score,Stress_Level,Sleep_Hours,Placement_Status,Expected_Salary_Lpa,Preferred_Programming_Language,Mental_Wellbeing_Score,Ai_Replaceability_Fear,Total_Screen_Time,Productivity_Per_Screentime
0,STU00001,17,Female,Mumbai,ENTC,3,8.56,3.6,4.4,6.5,...,64,9,6.1,Internship,34.38,C++,36,3,10.9,5.87
1,STU00002,19,Female,Nagpur,Civil,2,8.51,5.3,2.7,6.6,...,97,7,6.2,Placed,4.91,Java,30,6,9.3,10.43
2,STU00003,28,Female,Mumbai,CSE,2,7.25,7.6,1.4,4.8,...,58,7,6.7,Internship,23.30,C++,90,1,6.2,9.35
3,STU00004,21,Female,Nagpur,ENTC,2,9.24,7.5,5.8,2.9,...,73,10,5.8,Not Placed,10.30,JavaScript,95,7,8.7,8.39
4,STU00005,27,Female,Nagpur,ENTC,3,6.79,6.7,3.5,3.9,...,94,3,6.5,Internship,16.63,JavaScript,63,3,7.4,12.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,STU02996,20,Male,Kolkata,ENTC,3,8.28,7.4,2.3,2.1,...,78,8,8.6,Placed,26.09,Python,75,6,4.4,17.73
2996,STU02997,25,Male,Hyderabad,AI/ML,3,6.21,3.8,7.7,4.9,...,65,8,7.1,Placed,23.23,JavaScript,34,10,12.6,5.16
2997,STU02998,23,Male,Chennai,Electrical,4,6.50,9.4,7.0,7.9,...,52,6,5.1,Placed,25.05,JavaScript,66,2,14.9,3.49
2998,STU02999,18,Female,Bangalore,AI/ML,1,9.32,8.8,7.3,0.4,...,95,8,8.2,Internship,22.46,Java,76,8,7.7,12.34
2999,STU03000,19,Female,Hyderabad,Civil,3,9.63,7.7,4.4,0.7,...,98,6,8.0,Placed,21.27,Java,40,1,5.1,19.22

In [27]:
#Descriptive statistics
# Mean, median, mode, variance, standard deviation, Range
columns = ["CGPA", "Daily_Study_Hours","Mental_Wellbeing_Score","Ai_Replaceability_Fear","Total_Screen_Time",
           "Expected_Salary_Lpa","Productivity_Score","Stress_Level","Sleep_Hours"]

for s in columns:
    print(s)
    print(f"Mean = {students[s].mean()}")
    print(f"Median = {students[s].median()}")
    print(f"Mode = {students[s].mode()[0]}")
    print(f"Variance = {students[s].var()}")
    print(f"SD = {students[s].std()}")

CGPA
Mean = 7.712243333333333
Median = 7.73
Mode = 9.57
Variance = 1.635149717361342
SD = 1.278729728035343
Daily_Study_Hours
Mean = 5.511399999999999
Median = 5.5
Mode = 5.1
Variance = 6.775228449483148
SD = 2.6029269005262416
Mental_Wellbeing_Score
Mean = 65.08
Median = 65.0
Mode = 73
Variance = 415.8502167389136
SD = 20.392405859508425
Ai_Replaceability_Fear
Mean = 5.514333333333333
Median = 6.0
Mode = 3
Variance = 8.377920529065273
SD = 2.8944637722841295
Total_Screen_Time
Mean = 8.5019
Median = 8.4
Mode = 7.5
Variance = 11.797572247415685
SD = 3.4347594162351
Expected_Salary_Lpa
Mean = 18.720813333333336
Median = 18.78
Mode = 16.1
Variance = 83.65085522356354
SD = 9.146084146975882
Productivity_Score
Mean = 70.19866666666667
Median = 70.0
Mode = 98
Variance = 313.8044663776815
SD = 17.714526987127865
Stress_Level
Mean = 5.429333333333333
Median = 5.0
Mode = 5
Variance = 8.124381015894174
SD = 2.8503299836850777
Sleep_Hours
Mean = 6.488199999999999
Median = 6.5
Mode = 5.1
Variance = 2.07316514838279
SD = 1.4398490019383248

In [28]:
# Range

numerical_columns = students.select_dtypes(include = ['float64','int64']).columns
print(numerical_columns)

for r in numerical_columns:
    print(r)
    minimum = min(students[r])
    print(f"minimum : {minimum}")
    maximum = max(students[r])
    print(f"maximum : {maximum}")
    Range = maximum - minimum
    print(f"Range : {Range}")

Index(['Age', 'Year_Of_Study', 'CGPA', 'Daily_Study_Hours',
       'Daily_Chatgpt_Usage_Hours', 'Daily_Coding_Hours', 'Productivity_Score',
       'Stress_Level', 'Sleep_Hours', 'Expected_Salary_Lpa',
       'Mental_Wellbeing_Score', 'Ai_Replaceability_Fear', 'Total_Screen_Time',
       'Productivity_Per_Screentime'],
      dtype='object')
Age
minimum : 17
maximum : 28
Range : 11
Year_Of_Study
minimum : 1
maximum : 4
Range : 3
CGPA
minimum : 5.5
maximum : 9.9
Range : 4.4
Daily_Study_Hours
minimum : 1.0
maximum : 10.0
Range : 9.0
Daily_Chatgpt_Usage_Hours
minimum : 0.0
maximum : 8.0
Range : 8.0
Daily_Coding_Hours
minimum : 0.0
maximum : 9.0
Range : 9.0
Productivity_Score
minimum : 40
maximum : 100
Range : 60
Stress_Level
minimum : 1
maximum : 10
Range : 9
Sleep_Hours
minimum : 4.0
maximum : 9.0
Range : 5.0
Expected_Salary_Lpa
minimum : 3.0
maximum : 34.97
Range : 31.97
Mental_Wellbeing_Score
minimum : 30
maximum : 100
Range : 70
Ai_Replaceability_Fear
minimum : 1
maximum : 10
Range : 9
Total_Screen_Time
minimum : 0.3
maximum : 16.9
Range : 16.599999999999998
Productivity_Per_Screentime
minimum : 2.58
maximum : 310.0
Range : 307.42

In [29]:
#correlation
# to check whether daily study hours and CGPA are related
#(ie.,does CGPA increases when study hours increases)

from scipy import stats

correlation, p_value = stats.pearsonr(students["Daily_Study_Hours"], students["CGPA"])

print(f"Correlation : {correlation}")
print(f"p-value : {p_value}")

#H0 : there is no relationship between study hours and CGPA(correlation = 0)
#H1 : there is a significant relationship between study hours and CGPA(correlation != 0)

if correlation > 0:
    print("There is a positive relationship")
elif correlation == 0:
    print("There is no relationship")
else:
    print("There is a negative relationship")

#p_value

alpha = 0.05

if p_value < alpha:
    print("Reject H0, there is a relationship between study hours and CGPA")
else:
    print("Failed to reject H0, there is no relationship between study hours and CGPA")

Correlation : 0.005625859081739713
p-value : 0.7580709086113466
There is a positive relationship
Failed to reject H0, there is no relationship between study hours and CGPA

In [30]:
#Two sample t-test - two tailed
# To check whether the CGPA of students with high ai dependency level and low ai dependency level are same or different.

High_ai_dependency = students[students["Ai_Dependency_Level"] == "High"]["CGPA"]
Low_ai_dependency = students[students["Ai_Dependency_Level"] == "Low"]["CGPA"]

print(High_ai_dependency)
print(Low_ai_dependency)

print(f"Average CGPA of students with High_ai_dependency = {High_ai_dependency.mean()}")
print(f"Average CGPA of students with Low_ai_dependency = {Low_ai_dependency.mean()}")

from scipy.stats import ttest_ind

#H0 : There is no difference between the average CGPA of students with high ai dependency level and low ai dependency level
#H1 : There is a significant difference between the average CGPA of students with high ai dependency level and low ai dependency level

t_statistic, p_value = ttest_ind(High_ai_dependency, Low_ai_dependency)
print(f"t-statistic = {t_statistic}") # average cgpa of students with high ai dependency level is very slightly
                                      # (only in numeric values but generally no difference) lower than 
                                      # that of students with low ai dependency.
print(f"p-value = {p_value}")

alpha = 0.05

if p_value < alpha:
    print("Reject H0, there is a significant difference  between the CGPA of students with high ai dependency level and low ai dependency level")
else:
    print("Failed to reject H0,There is no difference between the CGPA of students with high ai dependency level and low ai dependency level")

3       9.24
5       6.87
12      9.57
16      6.25
17      9.85
        ...
2972    8.24
2978    6.56
2979    7.58
2980    9.18
2981    6.80
Name: CGPA, Length: 1000, dtype: float64
0       8.56
1       8.51
2       7.25
4       6.79
7       8.20
        ...
2995    8.28
2996    6.21
2997    6.50
2998    9.32
2999    9.63
Name: CGPA, Length: 1033, dtype: float64
Average CGPA of students with High_ai_dependency = 7.6944799999999995
Average CGPA of students with Low_ai_dependency = 7.721006776379477
t-statistic = -0.4685842144439853
p-value = 0.6394171494927553
Failed to reject H0,There is no difference between the CGPA of students with high ai dependency level and low ai dependency level

In [31]:
#probability
# There are 3000 students.If i choose one student at random, what is probability of 
# choosing a student with productivity score more than 85?

total_students = len(students)
print(total_students)
productivity_score_greater_than_85 = len(students[students["Productivity_Score"] >= 85])
print(productivity_score_greater_than_85)

probability = productivity_score_greater_than_85/total_students
print(probability)
print(f"The probability of choosing a student at random with productivity score more than 85 is {round(probability * 100,2)}%")

3000
807
0.269
The probability of choosing a student at random with productivity score more than 85 is 26.9%

In [32]:
#Anova
# To check if there is a difference in atleast one among the average AI replaceability fear of students in different branches.
unique_branch = students["Branch"].unique()
print(unique_branch)

branchwise_ai_replaceability_fear = []
for ub in unique_branch:
    ai_fear = students[students["Branch"] == ub]["Ai_Replaceability_Fear"]
    print(ub)
    print(ai_fear)
    average = ai_fear.mean()
    print(f"Average : {average}")
    branchwise_ai_replaceability_fear.append(ai_fear)
print(branchwise_ai_replaceability_fear)

#H0 : There is no difference among the average AI replaceability fear of students in different branches 
#H1 : There is a difference in atleast one among the average AI replaceability fear of students in different branches

from scipy.stats import f_oneway

f_statistic, p_value = f_oneway(*branchwise_ai_replaceability_fear)
print(f"f_statistic : {f_statistic}")
print(f"p-value : {p_value}")

alpha = 0.05
if p_value < alpha:
    print("Reject H0, There is a difference in atleast one among the average AI replaceability fear of students in differnt branches")
else:
    print("Failed to reject H0, There is no difference among the average AI replaceability fear of students in differnt branches")

['ENTC' 'Civil' 'CSE' 'Mechanical' 'AI/ML' 'Electrical' 'IT']
ENTC
0       3
3       7
4       3
19      1
28      4
       ..
2930    4
2937    3
2953    8
2984    7
2995    6
Name: Ai_Replaceability_Fear, Length: 429, dtype: int64
Average : 5.37995337995338
Civil
1       6
8       7
15      6
20      4
27      3
       ..
2966    2
2971    5
2975    6
2980    9
2999    1
Name: Ai_Replaceability_Fear, Length: 414, dtype: int64
Average : 5.528985507246377
CSE
2       1
5       1
7       1
9       4
17      5
       ..
2967    4
2976    3
2978    4
2981    3
2987    3
Name: Ai_Replaceability_Fear, Length: 463, dtype: int64
Average : 5.501079913606912
Mechanical
6        9
10       6
11       8
12      10
18      10
        ..
2973     8
2977     1
2983     5
2988     7
2990     3
Name: Ai_Replaceability_Fear, Length: 438, dtype: int64
Average : 5.739726027397261
AI/ML
13       4
14       8
31       4
47       3
56       7
        ..
2974    10
2992     9
2993     4
2996    10
2998     8
Name: Ai_Replaceability_Fear, Length: 426, dtype: int64
Average : 5.427230046948357
Electrical
16      6
24      8
29      7
30      7
35      6
       ..
2948    9
2951    1
2954    4
2994    8
2997    2
Name: Ai_Replaceability_Fear, Length: 428, dtype: int64
Average : 5.5514018691588785
IT
23      2
26      8
33      6
53      1
77      3
       ..
2982    7
2985    1
2986    6
2989    8
2991    5
Name: Ai_Replaceability_Fear, Length: 402, dtype: int64
Average : 5.465174129353234
[0       3
3       7
4       3
19      1
28      4
       ..
2930    4
2937    3
2953    8
2984    7
2995    6
Name: Ai_Replaceability_Fear, Length: 429, dtype: int64, 1       6
8       7
15      6
20      4
27      3
       ..
2966    2
2971    5
2975    6
2980    9
2999    1
Name: Ai_Replaceability_Fear, Length: 414, dtype: int64, 2       1
5       1
7       1
9       4
17      5
       ..
2967    4
2976    3
2978    4
2981    3
2987    3
Name: Ai_Replaceability_Fear, Length: 463, dtype: int64, 6        9
10       6
11       8
12      10
18      10
        ..
2973     8
2977     1
2983     5
2988     7
2990     3
Name: Ai_Replaceability_Fear, Length: 438, dtype: int64, 13       4
14       8
31       4
47       3
56       7
        ..
2974    10
2992     9
2993     4
2996    10
2998     8
Name: Ai_Replaceability_Fear, Length: 426, dtype: int64, 16      6
24      8
29      7
30      7
35      6
       ..
2948    9
2951    1
2954    4
2994    8
2997    2
Name: Ai_Replaceability_Fear, Length: 428, dtype: int64, 23      2
26      8
33      6
53      1
77      3
       ..
2982    7
2985    1
2986    6
2989    8
2991    5
Name: Ai_Replaceability_Fear, Length: 402, dtype: int64]
f_statistic : 0.6950533311603877
p-value : 0.653655802169541
Failed to reject H0, There is no difference among the average AI replaceability fear of students in differnt branches

In [33]:
students

,Student_Id,Age,Gender,City,Branch,Year_Of_Study,CGPA,Daily_Study_Hours,Daily_Chatgpt_Usage_Hours,Daily_Coding_Hours,...,Productivity_Score,Stress_Level,Sleep_Hours,Placement_Status,Expected_Salary_Lpa,Preferred_Programming_Language,Mental_Wellbeing_Score,Ai_Replaceability_Fear,Total_Screen_Time,Productivity_Per_Screentime
0,STU00001,17,Female,Mumbai,ENTC,3,8.56,3.6,4.4,6.5,...,64,9,6.1,Internship,34.38,C++,36,3,10.9,5.87
1,STU00002,19,Female,Nagpur,Civil,2,8.51,5.3,2.7,6.6,...,97,7,6.2,Placed,4.91,Java,30,6,9.3,10.43
2,STU00003,28,Female,Mumbai,CSE,2,7.25,7.6,1.4,4.8,...,58,7,6.7,Internship,23.30,C++,90,1,6.2,9.35
3,STU00004,21,Female,Nagpur,ENTC,2,9.24,7.5,5.8,2.9,...,73,10,5.8,Not Placed,10.30,JavaScript,95,7,8.7,8.39
4,STU00005,27,Female,Nagpur,ENTC,3,6.79,6.7,3.5,3.9,...,94,3,6.5,Internship,16.63,JavaScript,63,3,7.4,12.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,STU02996,20,Male,Kolkata,ENTC,3,8.28,7.4,2.3,2.1,...,78,8,8.6,Placed,26.09,Python,75,6,4.4,17.73
2996,STU02997,25,Male,Hyderabad,AI/ML,3,6.21,3.8,7.7,4.9,...,65,8,7.1,Placed,23.23,JavaScript,34,10,12.6,5.16
2997,STU02998,23,Male,Chennai,Electrical,4,6.50,9.4,7.0,7.9,...,52,6,5.1,Placed,25.05,JavaScript,66,2,14.9,3.49
2998,STU02999,18,Female,Bangalore,AI/ML,1,9.32,8.8,7.3,0.4,...,95,8,8.2,Internship,22.46,Java,76,8,7.7,12.34
2999,STU03000,19,Female,Hyderabad,Civil,3,9.63,7.7,4.4,0.7,...,98,6,8.0,Placed,21.27,Java,40,1,5.1,19.22

In [34]:
students.to_csv("indian_students_ai_dataset.csv",index = False)